### ISSUE TITLE
User Specific Join Link

### ISSUE THREAD

**Issue by hamish-compucorp** [lcdservices/biz.lcdservices.civizoom#1]
Hi,

I'm having trouble with the following part of the extension:
`In addition, the user-specific join URL is stored in the event registration and can be referenced in emails and scheduled reminders through tokens.`

I can't find any reference to a join url in the event registration, and when creating a scheduled reminder, there doesn't appear to be a token for the zoom link. Is this an event token, and is there a way to manually insert the correct token?

Best,

Hamish

**Comment by lcdservices** [comment]
When you view or edit a registration, do you see a set of custom fields visible?
Or when you view your custom fields (Administer > Customize Data and Screens > Custom Fields) -- you should see a set called "CiviZoom Registrant"

**Comment by hamish-compucorp** [comment]
Hi,

Thanks so much for coming back on this.
The custom field is visible on an a person's event record, and visible in the custom fields area of civi.
The problem I'm having is that the field isn't visible in the tokens drop down when creating a scheduled reminder, and there doesn't seem to be an obvious way to create the correct token from scratch (e.g. {participant.custom_54})

Best,

Hamish

**Comment by lcdservices** [comment]
There's nothing special about the custom fields. We create them during the extension installation and then store the Zoom registration ID and Join URL when we register the person in Zoom. So if they're not exposed to schedule reminders as expected, that's an issue with Core CiviCRM.

I found this issue: https://lab.civicrm.org/dev/core/-/issues/348
It seems to indicate participant tokens are not currently supported in schedule reminders. But there is a PR in the last comment that has been proposed. You could try implementing that and if it works in your testing, update the ticket and PR to indicate that. The PR comments and review seem to have stalled a bit. Maybe you can help push that forward.

**Comment by hamish-compucorp** [comment]
Hi,

Ah right, it looks like the token is not supported, I'll take a look in the PR and see if I can move things.
Otherwise it might be worth removing the reference to tokens in scheduled reminders until this works.
Is there any other conceivable way of including the user's unique join code in an email?
It would be great to be able to send this from civi rather than the zoom default one.

Thanks,

Hamish

**Comment by lcdservices** [comment]
In the issue referenced above there is discussion about another extension that adds support for pdf letters to events, but also includes support for participant custom fields in scheduled reminders: https://github.com/DizzyMissLizzy/be.dizzymisslizzy.pdfletterevents

I've not used it -- I'm just suggesting it based on the discussion.
It's also possible CiviRules could be used. There's been recent work on tokens in core that was prompted in part by CiviRules and was seeking to provide better contextual support (i.e. to be better aware when the context was a participant record, etc.).
