### ISSUE TITLE
Performance issues when opening events/participants related pages

### ISSUE THREAD

**Issue by ritatorok** [lcdservices/biz.lcdservices.civizoom#2]
Hi,

We have some performance issues on event/participant related pages when the CiviZoom extension is configured.

**Reproduction steps:**
1. Enable CiviZoom extension
2. Configure civizoom extension /civicrm/admin/setting/civizoom
3. add valid keys
4. select the appropriate statuses
5. Save the settings
6. Go to Participant search → **you will see that the page loads in about 22 seconds (on another site 36s) which is too long**
7. Go back to civizoom extension settings, and remove the zoom keys and save
8. Visit the participant search again → **it loads in 2 seconds which is good**

I was checking the loading times in the developer console Network tab while opening the pages. 
I was testing on Civi version 5.35.2

Enabling the extension doesn’t trigger the performance issues, but if you configure the civizoom settings and add the “Zoom JWT API Key” and “Zoom JWT API Secret” and save the settings, you will have performance issues when visiting the participant search, event dashboard, etc. pages. You have to use valid civizoom keys to see the problem, doesn’t work with any random test keys. 

Have you met this issue before? Please let me know if there are any zoom account settings, or civi settings that we might need to change to improve the performance of those event related pages!

Thanks
Rita

**Comment by hamish-compucorp** [comment]
Hi @lcdservices - I'm a colleague of Rita above, please could i follow up on this?
Have you seen any similar issues?

Best,

Hamish

**Comment by ritatorok** [comment]
Hello @lcdservices , is there any update on this please? :) 
Thanks
Rita

**Comment by ufundo** [comment]
Also experiencing this.

It looks like https://github.com/lcdservices/biz.lcdservices.civizoom/blob/0beda3fceb30f60f80df279e4389e7958a3731d3/civizoom.php#L163 polls Zoom for all of your meeting details during the load of event pages, which I guess is what hangs.

Imagine the solution would be caching the results or making the call asynchronously - neither trivial solutions though...?

**Comment by lcdservices** [comment]
latest release addresses some of these issues and should improve performance.
