### ISSUE TITLE
Multiple issues with CiviZoom extension

### ISSUE THREAD

**Issue by flantascience** [lcdservices/biz.lcdservices.civizoom#3]
Hi -

I've installed the CiviZoom extension v 2.20 and added the required API keys to the Settings page.

When a user registers on our Civi Event page, they get a confirmation email from Civi (if we have that enabled) which does not include the Zoom link info.  The user does not get added to the list of registrants inside of Zoom.

Alternatively, if I disable the Civi confirmation email, they get an email from Zoom which does contain a link.  However, they do not get added to the Zoom list of registrants.  What's also strange here, is that if we have Authentication Required disabled from Attendees, the email to the registrant refers to them as a Panelist instead of an Attendee.  Authentication Required is difficult for us as this would require every single attendee to register for a Zoom account.

We're not really super concerned with users no showing up in the Zoom registrants list, though it does seem like this would be working if everything was at 100%.  The main concern here, is that when a user registers for the event, they're not getting the event URL to join the event at all.

Edit: when Authentication Required is disabled and Civi's confirmation email is disabled, I'm not getting any confirmation emails from Zoom and the user doesn't show up in Zoom's registration.  It's very confusing, because inside of Civi, I can find the users unique URL for the Zoom event.  But it's not being sent to them at all.

**Comment by lcdservices** [comment]
Closing as there have been several versions released since this issue was filed.
